version: "3.8"

services:
  db:
    image: postgres:14.6
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT}
    networks:
      - main

  app:
    build:
      context: .
    env_file:
      - .env
    networks:
      - main
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/app

networks:
  main:

volumes:
  database-data: